import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { satoshi, integral } from "@/app/ui/fonts"
import { SpeedInsights } from '@vercel/speed-insights/next';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${integral.variable}`}
      >
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
